import React, { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import UAuth from '@uauth/js';

const uauth = new UAuth({
  clientID: process.env.NEXT_PUBLIC_UNSTOPPABLEDOMAINS_CLIENTID,
  redirectUri: process.env.NEXT_PUBLIC_UNSTOPPABLEDOMAINS_REDIRECT_URI,
  scope: "openid wallet"
});

export default function Home() {
  const [domainData, setDomainData] = useState(null);

  const loginWithUnstoppableDomains = async () => {
    try {
      const authorization = await uauth.loginWithPopup();
      authorization.sub = authorization.idToken.sub;
      console.log(authorization);

      setDomainData(authorization);
      connectWallet();
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={loginWithUnstoppableDomains}>
        Login with Unstoppable
      </button>
      <p>{JSON.stringify(domainData)}</p>

    </div>
  )
}
